---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - weatherapp.weather.api
  resources:
  - weatherapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - weatherapp.weather.api
  resources:
  - weatherapis/finalizers
  verbs:
  - update
- apiGroups:
  - weatherapp.weather.api
  resources:
  - weatherapis/status
  verbs:
  - get
  - patch
  - update
