# permissions for end users to edit weatherapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: weatherapi-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: weather
    app.kubernetes.io/part-of: weather
    app.kubernetes.io/managed-by: kustomize
  name: weatherapi-editor-role
rules:
- apiGroups:
  - weatherapp.weather.api
  resources:
  - weatherapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - weatherapp.weather.api
  resources:
  - weatherapis/status
  verbs:
  - get
